/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.ac.bg.fon.ps.view.form;

import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Mirko
 */
public class FrmDailySchedule extends javax.swing.JDialog {

    /**
     * Creates new form FrmDailySchedule
     */
    public FrmDailySchedule(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblManifestacija = new javax.swing.JLabel();
        cbManifestacija = new javax.swing.JComboBox<>();
        lblTrajanje = new javax.swing.JLabel();
        txtDatumOd = new javax.swing.JTextField();
        txtDatumDo = new javax.swing.JTextField();
        lblCrtica = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblIzlagaciDatuma = new javax.swing.JTable();
        lblDatum = new javax.swing.JLabel();
        cbDatum = new javax.swing.JComboBox<>();
        btnIzbrisiIzlagaca = new javax.swing.JButton();
        panelIzlagac = new javax.swing.JPanel();
        lblIzlagac = new javax.swing.JLabel();
        cbIzlagac = new javax.swing.JComboBox<>();
        lblHala = new javax.swing.JLabel();
        cbHala = new javax.swing.JComboBox<>();
        lblStand = new javax.swing.JLabel();
        cbStand = new javax.swing.JComboBox<>();
        btnDodajIzlagaca = new javax.swing.JButton();
        btnOmoguciIzmene = new javax.swing.JButton();
        btnIzmeniDnevniRaspored = new javax.swing.JButton();
        btnObrisiDnevniRaspored = new javax.swing.JButton();
        btnPonisti = new javax.swing.JButton();
        btnSacuvaj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblManifestacija.setText("Manifestacija:");

        lblTrajanje.setText("Trajanje:");

        txtDatumOd.setEditable(false);

        txtDatumDo.setEditable(false);

        lblCrtica.setText("-");

        tblIzlagaciDatuma.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblIzlagaciDatuma);

        lblDatum.setText("Datum:");

        btnIzbrisiIzlagaca.setText("Izbrisi Izlagaca");

        panelIzlagac.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblIzlagac.setText("Izlagac:");

        lblHala.setText("Hala:");

        lblStand.setText("Stand:");

        btnDodajIzlagaca.setText("Dodaj Izlagaca");

        javax.swing.GroupLayout panelIzlagacLayout = new javax.swing.GroupLayout(panelIzlagac);
        panelIzlagac.setLayout(panelIzlagacLayout);
        panelIzlagacLayout.setHorizontalGroup(
            panelIzlagacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIzlagacLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelIzlagacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelIzlagacLayout.createSequentialGroup()
                        .addGroup(panelIzlagacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIzlagac)
                            .addComponent(lblStand)
                            .addComponent(lblHala))
                        .addGap(18, 18, 18)
                        .addGroup(panelIzlagacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbIzlagac, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbHala, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbStand, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelIzlagacLayout.createSequentialGroup()
                        .addComponent(btnDodajIzlagaca)
                        .addGap(45, 45, 45))))
        );
        panelIzlagacLayout.setVerticalGroup(
            panelIzlagacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIzlagacLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panelIzlagacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIzlagac)
                    .addComponent(cbIzlagac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(panelIzlagacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHala)
                    .addComponent(cbHala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelIzlagacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStand)
                    .addComponent(cbStand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnDodajIzlagaca)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnOmoguciIzmene.setText("Omoguci Izmene");

        btnIzmeniDnevniRaspored.setText("Izmeni dnevni raspored");

        btnObrisiDnevniRaspored.setText("Obrisi dnevni raspored");

        btnPonisti.setText("Odustani");

        btnSacuvaj.setText("Sacuvaj");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnOmoguciIzmene, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnIzmeniDnevniRaspored, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnObrisiDnevniRaspored)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                        .addComponent(btnIzbrisiIzlagaca)
                        .addGap(68, 68, 68))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(lblTrajanje)
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblManifestacija)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDatum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbManifestacija, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtDatumOd, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCrtica)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDatumDo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelIzlagac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSacuvaj, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnPonisti, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblManifestacija)
                            .addComponent(cbManifestacija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTrajanje)
                            .addComponent(txtDatumDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCrtica)
                            .addComponent(txtDatumOd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDatum)
                            .addComponent(cbDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelIzlagac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(btnIzbrisiIzlagaca)
                        .addGap(61, 61, 61)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnOmoguciIzmene)
                            .addComponent(btnIzmeniDnevniRaspored)
                            .addComponent(btnObrisiDnevniRaspored))
                        .addGap(58, 58, 58))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSacuvaj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPonisti)
                        .addGap(6, 6, 6))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public JButton getBtnDodajIzlagaca() {
        return btnDodajIzlagaca;
    }

    public JButton getBtnIzbrisiIzlagaca() {
        return btnIzbrisiIzlagaca;
    }

    public JButton getBtnIzmeniDnevniRaspored() {
        return btnIzmeniDnevniRaspored;
    }

    public JButton getBtnObrisiDnevniRaspored() {
        return btnObrisiDnevniRaspored;
    }

    public JButton getBtnOmoguciIzmene() {
        return btnOmoguciIzmene;
    }

    public JButton getBtnPonisti() {
        return btnPonisti;
    }

    public JButton getBtnSacuvaj() {
        return btnSacuvaj;
    }

    public JComboBox<Object> getCbDatum() {
        return cbDatum;
    }

    public JComboBox<Object> getCbHala() {
        return cbHala;
    }

    public JComboBox<Object> getCbIzlagac() {
        return cbIzlagac;
    }

    public JComboBox<Object> getCbManifestacija() {
        return cbManifestacija;
    }

    public JComboBox<Object> getCbStand() {
        return cbStand;
    }

    public void setCbStand(JComboBox<Object> cbStand) {
        this.cbStand = cbStand;
    }

    public JPanel getPanelIzlagac() {
        return panelIzlagac;
    }

    public JTable getTblIzlagaciDana() {
        return tblIzlagaciDatuma;
    }

    public JTextField getTxtDatumDo() {
        return txtDatumDo;
    }

    public JTextField getTxtDatumOd() {
        return txtDatumOd;
    }

    public JLabel getLblDatum() {
        return lblDatum;
    }

    public JLabel getLblHala() {
        return lblHala;
    }

    public JLabel getLblIzlagac() {
        return lblIzlagac;
    }

    public JLabel getLblManifestacija() {
        return lblManifestacija;
    }

    public JLabel getLblStand() {
        return lblStand;
    }

    public JLabel getLblTrajanje() {
        return lblTrajanje;
    }

    public JTable getTblIzlagaciDatuma() {
        return tblIzlagaciDatuma;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajIzlagaca;
    private javax.swing.JButton btnIzbrisiIzlagaca;
    private javax.swing.JButton btnIzmeniDnevniRaspored;
    private javax.swing.JButton btnObrisiDnevniRaspored;
    private javax.swing.JButton btnOmoguciIzmene;
    private javax.swing.JButton btnPonisti;
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JComboBox<Object> cbDatum;
    private javax.swing.JComboBox<Object> cbHala;
    private javax.swing.JComboBox<Object> cbIzlagac;
    private javax.swing.JComboBox<Object> cbManifestacija;
    private javax.swing.JComboBox<Object> cbStand;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCrtica;
    private javax.swing.JLabel lblDatum;
    private javax.swing.JLabel lblHala;
    private javax.swing.JLabel lblIzlagac;
    private javax.swing.JLabel lblManifestacija;
    private javax.swing.JLabel lblStand;
    private javax.swing.JLabel lblTrajanje;
    private javax.swing.JPanel panelIzlagac;
    private javax.swing.JTable tblIzlagaciDatuma;
    private javax.swing.JTextField txtDatumDo;
    private javax.swing.JTextField txtDatumOd;
    // End of variables declaration//GEN-END:variables

    // Dodavanje action listenera ComboBox komponentama
    public void addCbManifestacijaActionListener(ActionListener actionListener) {
        cbManifestacija.addActionListener(actionListener);
    }

    public void addCbDatumActionListener(ActionListener actionListener) {
        cbDatum.addActionListener(actionListener);
    }

    public void addCbHalaActionListener(ActionListener actionListener) {
        cbHala.addActionListener(actionListener);
    }

    public void addCbStandActionListener(ActionListener actionListener) {
        cbStand.addActionListener(actionListener);
    }

    // Dodavanje action listenera Button komponentama
    public void addDodajIzlagacaActionListener(ActionListener actionListener) {
        btnDodajIzlagaca.addActionListener(actionListener);
    }

    public void addIzbrisiIzlagacaActionListener(ActionListener actionListener) {
        btnIzbrisiIzlagaca.addActionListener(actionListener);
    }

    public void addOmoguciIzmeneActionListener(ActionListener actionListener) {
        btnOmoguciIzmene.addActionListener(actionListener);
    }

    public void addIzmeniActionListener(ActionListener actionListener) {
        btnIzmeniDnevniRaspored.addActionListener(actionListener);
    }

    public void addObrisiActionListener(ActionListener actionListener) {
        btnObrisiDnevniRaspored.addActionListener(actionListener);
    }

    public void addSacuvajDnevniRasporedActionListener(ActionListener actionListener) {
        btnSacuvaj.addActionListener(actionListener);
    }

    public void addPonistiActionListener(ActionListener actionListener) {
        btnPonisti.addActionListener(actionListener);
    }
}
