/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.ac.bg.fon.ps.view.form;

import java.awt.event.ActionListener;
import java.awt.event.FocusAdapter;
import java.awt.event.MouseAdapter;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Mirko
 */
public class FrmLogin extends javax.swing.JFrame {

    /**
     * Creates new form frmPrijavljivanjeStomatologa
     */
    public FrmLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPrijava = new javax.swing.JButton();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtSifra = new javax.swing.JPasswordField();
        lblSifra = new javax.swing.JLabel();
        cbSifra = new javax.swing.JCheckBox();
        panelJezik = new javax.swing.JPanel();
        lblIzaberiJezik = new javax.swing.JLabel();
        lblEngleskaZastava = new javax.swing.JLabel();
        lblSrpskaZastava = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setMinimumSize(new java.awt.Dimension(428, 300));
        setResizable(false);
        getContentPane().setLayout(null);

        btnPrijava.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnPrijava.setText("Prijavi se");
        btnPrijava.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 255, 51), null));
        getContentPane().add(btnPrijava);
        btnPrijava.setBounds(120, 220, 75, 30);

        lblEmail.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblEmail.setText("Email:");
        getContentPane().add(lblEmail);
        lblEmail.setBounds(30, 140, 90, 20);

        txtEmail.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(204, 204, 204));
        txtEmail.setText("Unesite email...");
        getContentPane().add(txtEmail);
        txtEmail.setBounds(130, 140, 240, 20);

        txtSifra.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txtSifra.setForeground(new java.awt.Color(204, 204, 204));
        txtSifra.setText("Unesite sifru...");
        getContentPane().add(txtSifra);
        txtSifra.setBounds(130, 180, 240, 20);

        lblSifra.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblSifra.setText("Šifra:");
        getContentPane().add(lblSifra);
        lblSifra.setBounds(30, 180, 90, 20);

        cbSifra.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        cbSifra.setText("Prikaži šifru");
        getContentPane().add(cbSifra);
        cbSifra.setBounds(220, 220, 180, 30);

        panelJezik.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIzaberiJezik.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        lblIzaberiJezik.setText("Izaberite jezik / Choose language");
        panelJezik.add(lblIzaberiJezik, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));
        panelJezik.add(lblEngleskaZastava, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 140, 60));
        panelJezik.add(lblSrpskaZastava, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 140, 60));

        getContentPane().add(panelJezik);
        panelJezik.setBounds(10, 10, 400, 120);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrijava;
    private javax.swing.JCheckBox cbSifra;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEngleskaZastava;
    private javax.swing.JLabel lblIzaberiJezik;
    private javax.swing.JLabel lblSifra;
    private javax.swing.JLabel lblSrpskaZastava;
    private javax.swing.JPanel panelJezik;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtSifra;
    // End of variables declaration//GEN-END:variables

    public JTextField getTxtEmail() {
        return txtEmail;
    }

    public JPasswordField getTxtSifra() {
        return txtSifra;
    }

    public JLabel getLblEmail() {
        return lblEmail;
    }

    public JButton getBtnPrijava() {
        return btnPrijava;
    }

    public JCheckBox getCbSifra() {
        return cbSifra;
    }

    public JLabel getLblEngleskaZastava() {
        return lblEngleskaZastava;
    }

    public JLabel getLblSrpskaZastava() {
        return lblSrpskaZastava;
    }

    public JLabel getLblSifra() {
        return lblSifra;
    }

    public void addLblSrpskiMouseClickedListener(MouseAdapter mouseAdapter) {
        lblSrpskaZastava.addMouseListener(mouseAdapter);
    }

    public void addLblEngleskiMouseClickedListener(MouseAdapter mouseAdapter) {
        lblEngleskaZastava.addMouseListener(mouseAdapter);
    }

    public void addTxtEmailFocusListener(FocusAdapter focusAdapter) {
        txtEmail.addFocusListener(focusAdapter);
    }

    public void addTxtPasswordFocusListener(FocusAdapter focusAdapter) {
        txtSifra.addFocusListener(focusAdapter);
    }

    public void addCbPasswordMouseClikedListener(ActionListener actionListener) {
        cbSifra.addActionListener(actionListener);
    }

    public void loginAddActionListener(ActionListener actionListener) {
        btnPrijava.addActionListener(actionListener);
    }

}
