/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.ac.bg.fon.ps.view.form;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JMenu;
import javax.swing.JMenuItem;

/**
 *
 * @author Mirko
 */
public class FrmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    public FrmMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPozadina = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JButton();
        menuMain = new javax.swing.JMenuBar();
        menuIzlagac = new javax.swing.JMenu();
        miNoviIzlagac = new javax.swing.JMenuItem();
        miPrikaziIzlagace = new javax.swing.JMenuItem();
        menuManifestacija = new javax.swing.JMenu();
        miNovaManifestacija = new javax.swing.JMenuItem();
        miPrikaziManifestacije = new javax.swing.JMenuItem();
        menuDnevniRaspored = new javax.swing.JMenu();
        miNoviDnevniRaspored = new javax.swing.JMenuItem();
        miPrikaziDnevneRasporede = new javax.swing.JMenuItem();
        menuPrazan = new javax.swing.JMenu();
        menuCurrentUser = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblPozadina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/ac/bg/fon/ps/images/belgradeFairLogo.png"))); // NOI18N

        btnLogOut.setText("Izloguj se");

        menuMain.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        menuIzlagac.setText("Izlagac");

        miNoviIzlagac.setText("Novi Izlagac");
        menuIzlagac.add(miNoviIzlagac);

        miPrikaziIzlagace.setText("Prikazi Izlagace");
        menuIzlagac.add(miPrikaziIzlagace);

        menuMain.add(menuIzlagac);

        menuManifestacija.setText("Manifestacija");

        miNovaManifestacija.setText("Nova manifestacija");
        menuManifestacija.add(miNovaManifestacija);

        miPrikaziManifestacije.setText("Pregledaj manifestacije");
        menuManifestacija.add(miPrikaziManifestacije);

        menuMain.add(menuManifestacija);

        menuDnevniRaspored.setText("Dnevni raspored");

        miNoviDnevniRaspored.setText("Novi Dnevni raspored");
        menuDnevniRaspored.add(miNoviDnevniRaspored);

        miPrikaziDnevneRasporede.setText("Prikazi Dnevne rasporede");
        menuDnevniRaspored.add(miPrikaziDnevneRasporede);

        menuMain.add(menuDnevniRaspored);

        menuPrazan.setText("                                                                                                                          ");
        menuPrazan.setEnabled(false);
        menuMain.add(menuPrazan);

        menuCurrentUser.setText("Ulogovani admin");
        menuMain.add(menuCurrentUser);

        setJMenuBar(menuMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(lblPozadina, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(304, 304, 304)
                        .addComponent(btnLogOut)))
                .addContainerGap(175, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(lblPozadina, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnLogOut)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogOut;
    private javax.swing.JLabel lblPozadina;
    private javax.swing.JMenu menuCurrentUser;
    private javax.swing.JMenu menuDnevniRaspored;
    private javax.swing.JMenu menuIzlagac;
    private javax.swing.JMenuBar menuMain;
    private javax.swing.JMenu menuManifestacija;
    private javax.swing.JMenu menuPrazan;
    private javax.swing.JMenuItem miNovaManifestacija;
    private javax.swing.JMenuItem miNoviDnevniRaspored;
    private javax.swing.JMenuItem miNoviIzlagac;
    private javax.swing.JMenuItem miPrikaziDnevneRasporede;
    private javax.swing.JMenuItem miPrikaziIzlagace;
    private javax.swing.JMenuItem miPrikaziManifestacije;
    // End of variables declaration//GEN-END:variables

    // IZLAGAC
    public void miExhibitorNewAddActionListener(ActionListener actionListener) {
        miNoviIzlagac.addActionListener(actionListener);
    }

    public void miExhibitorShowAllActionListener(ActionListener actionListener) {
        miPrikaziIzlagace.addActionListener(actionListener);
    }

    // MANIFESTACIJA
    public void miManifestationNewAddActionListener(ActionListener actionListener) {
        miNovaManifestacija.addActionListener(actionListener);
    }

    public void miManifestationShowAllActionListener(ActionListener actionListener) {
        miPrikaziManifestacije.addActionListener(actionListener);
    }

    // DNEVNI RASPORED
    public void miDailyScheduleAddActionListener(ActionListener actionListener) {
        miNoviDnevniRaspored.addActionListener(actionListener);
    }

    public void miDailyScheduleViewAllActionListener(ActionListener actionListener) {
        miPrikaziDnevneRasporede.addActionListener(actionListener);
    }

    // DUGME LOGOUT
    public void addBtnLogoutActionListener(ActionListener actionListener) {
        btnLogOut.addActionListener(actionListener);
    }

    // KORISNIK
    public JMenu getMenuCurrentUser() {
        return menuCurrentUser;
    }

    // Menu i itemi potrebni za promenu jezika
    public JButton getBtnLogOut() {
        return btnLogOut;
    }

    public JMenu getMenuDnevniRaspored() {
        return menuDnevniRaspored;
    }

    public JMenu getMenuIzlagac() {
        return menuIzlagac;
    }

    public JMenu getMenuManifestacija() {
        return menuManifestacija;
    }

    public JMenuItem getMiNovaManifestacija() {
        return miNovaManifestacija;
    }

    public JMenuItem getMiNoviDnevniRaspored() {
        return miNoviDnevniRaspored;
    }

    public JMenuItem getMiNoviIzlagac() {
        return miNoviIzlagac;
    }

    public JMenuItem getMiPrikazIzlagaca() {
        return miPrikaziIzlagace;
    }

    public JMenuItem getMiPrikaziDnevneRasporede() {
        return miPrikaziDnevneRasporede;
    }

    public JMenuItem getMiPrikaziManifestacije() {
        return miPrikaziManifestacije;
    }

}
